.TH Seq64cli "August 20 2018" "Version 0.95.2" "Seq64 Manual Page"

.SH NAME
Seq64 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B seq64cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]

.SH DESCRIPTION
.PP
\fISeq64cli\fP is the command-line (no GUI)
native JACK version of Sequencer64.  Please
see "man Sequencer64" for full information on this application.

.SH SEE ALSO
See the Sequencer64 man page for information.
See the Sequencer64-doc project for even more information.

