#!/bin/bash
#
# start_jack.sh from:
#
# https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit

jack_control start
jack_control ds alsa
jack_control dps device hw:HD2
jack_control dps rate 48000
jack_control dps nperiods 2
jack_control dps period 64
sleep 10
a2jmidid -e &
sleep 10
qjackctl &

