#!/bin/bash
#
#******************************************************************************
# packages (Sequencer64)
#------------------------------------------------------------------------------
##
# \file       	packages
# \library    	Sequencer64
# \author     	Chris Ahlstrom
# \date       	2018-09-29
# \update     	2018-10-29
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#  Packs up the current project directory, makes an NSIS package installer.
#  Written solely to automate some tedious stuff needed for an official
#  Sequencer64 release.
#
#-----------------------------------------------------------------------------

RELEASEMAJOR="0.96"
RELEASEMINOR="1"
RELEASENUMBER="$RELEASEMAJOR.$RELEASEMINOR"
REVNUMBER="0"
DODRYRUN="no"
DORELEASE="no"

if [ "$1" == "--help" ] || [ "$1" == "help" ] ; then

   cat << E_O_F

packages 0.2 2018-10-29

Usage:  ./pack [--dry-run] [--release 0.96.0]

This script packs the contents of the current directory into the following
packages:

E_O_F

else

   while [ "$1" != "" ] ; do

      case "$1" in

        --dry-run)
            DODRYRUN="yes"
            ;;

        --clean)
            DOCLEAN="yes"
            ;;

        --no-clean)
            DOCLEAN="no"
            ;;

        --release)
            shift
            DORELEASE="yes"
            RELEASENUMBER="$RELEASEMAJOR.$RELEASEMINOR"
            ;;

        *)
            ;;

      esac
      shift
   done

fi

PACKAGENAME="qpseq64-release-package-$RELEASENUMBER.7z"
INSTALLERNAME="sequencer64_setup_$RELEASENUMBER-$REVNUMBER.exe"
ZIPNAME="qpseq64-portable-$RELEASENUMBER-$REVNUMBER.zip"
TARNAME="sequencer64-master-rtmidi-$RELEASENUMBER.tar.xz"

if [ "$DODRYRUN" == "yes" ] ; then
   echo "Extracting Windows deployment package..."
   echo "$ 7z x $PACKAGENAME"
   echo "$ mv $PACKAGENAME .."
   echo "$ pushd nsis"
   echo "Building NSIS installer for release $RELEASENUMBER..."
   echo "$ makensis Seq64Setup.nsi"
   echo "$ popd"
   echo "$ cp release/$INSTALLERNAME ../sequencer64-packages/latest"
   echo "Making a portable Zip package..."
   echo "$ mv release/ qpseq64"
   echo "$ zip -q -u -r $ZIPNAME qpseq64/"
   echo "$ mv $ZIPNAME ../sequencer64-packages/latest"
   echo "Making a standard Linux source/configure tarball..."
#  echo "$ ./bootstrap --full-clean"
   echo "$ ./pack --release rtmidi 0.96.0"
   echo "$ mv ../$TARNAME ../sequencer64-packages/latest"
#  echo "$ rm -rf qpseq64/"
   echo "$ ls -lrt ../sequencer64-packages/latest"
else
   echo "Extracting Windows deployment package..."
   7z x $PACKAGENAME
   mv $PACKAGENAME ..
   pushd nsis
   echo "Building NSIS installer for release $RELEASENUMBER..."
   makensis Seq64Setup.nsi
   popd
   cp release/$INSTALLERNAME ../sequencer64-packages/latest
   echo "Making a portable Zip package..."
   mv release/ qpseq64
   zip -u -r $ZIPNAME qpseq64/
   mv $ZIPNAME ../sequencer64-packages/latest
   echo "Making a standard Linux source/configure tarball..."
#  ./bootstrap --full-clean
   ./pack --release rtmidi $RELEASENUMBER
   mv ../$TARNAME ../sequencer64-packages/latest
#  rm -rf qpseq64/
   ls -lrt ../sequencer64-packages/latest
fi

#******************************************************************************
# packages (Sequencer64)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 et ft=sh
#------------------------------------------------------------------------------
